# ClusterRole granting access to deployments
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-clusterrole
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]

---
# ClusterRoleBinding linking the ClusterRole to your service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: autoscaler
    namespace: microservices
roleRef:
  kind: ClusterRole
  name: autoscaler-clusterrole
  apiGroup: rbac.authorization.k8s.io
